### ISSUE TITLE
[Feature] Default State on Demos

### ISSUE THREAD

**Issue by R-Bower** [skoropadas/ng-doc#16]
### Description

I'd like to be able to supply default state to the `NgDocActions.demo` module.  Currently, the following options are static:
1. When a demo opens, it always seems to open on the TypeScript tab.  Sometimes I want to open on the HTML tab.  
2. When a page first loads, all demo code is collapsed.  I'd like the option to set the initial "expanded" state of each demo individually.

### Proposed solution

Allow us to supply additional parameters to the demo markdown configuration.  Something like the following:

```
{{ NgDocActions.demo("ButtonDemoComponent", {container: false, initialShow: true, defaultPane: "HTML"}) }}
```

### Alternatives considered

None

**Comment by skoropadas** [comment]
Good point, I will add it to the next release but rename the properties if you don't mind:

```twig
{{ NgDocActions.demo("ButtonDemoComponent", {container: false, expanded: true, defaultTab: "HTML"}) }}
```

**Comment by R-Bower** [comment]
Just sourced the most recent version and this is awesome.  Another idea I had:
MUI does something similar to this with a preview of sorts.  https://mui.com/material-ui/react-button/#basic-button Wondering if this would be possible with ng-doc.  The default preview is shown until the user expands the full example.

**Comment by skoropadas** [comment]
@R-Bower this is sick and I could easily do it, but for this a JIT Compiler is needed because obviously the component is compiled in the browser, but the JIT Compiler is marked as deprecated, while the Angular team still has not decided what its replacement will look like https://github.com/angular/angular/issues/43120. I believe that using the JIT Compiler in a documentation application is not a big problem and I could start using it, I'm just afraid if they decide to remove JIT Compiler, new solution may not support such view generation as you have shown.

**Comment by R-Bower** [comment]
@skoropadas I get that.  A live demo would be awesome.  I wonder what the Angular team is planning, re: truly dynamic components like we see in live demos.
