### ISSUE TITLE
[Feature] Separate page for each API scope

### ISSUE THREAD

**Issue by semicolin** [skoropadas/ng-doc#23]
### Description

When I add an API Entity with multiple scopes, the API List gets very long and I need to do a lot of scrolling to find the scope that I want. Setting the `order` property of `NgDocApiScope` does not change the order in the API List.

### Proposed solution

When I add an API Entity that includes multiple scopes, I want to show the API List for each scope on a separate page. I want the main "API" link in the sidebar to act like a category so I can expand it to see the list of scopes and click on one of them to go to the API List for that scope.

### Alternatives considered

- Put a "Scope" filter at the top of the API List next to the "Filter" and "Type" controls
- Just fix the behavior of `NgDocApiScope.order`

**Comment by skoropadas** [comment]
I was thinking about displaying scopes as pages, inside the API category, and that's why I didn't do it:

A user who is not familiar with the scopes of your project will most likely prefer to see a list of all entities and search among the entire list by name or by type, and if there are matches in several scopes, he will choose the entity that is necessary based on the context. 

So I think to make this logic work better I need to add a filter for scopes, as you suggested, and of course, fix the `order` property. Correct me if I missed something.

**Comment by semicolin** [comment]
One other alternative might be to allow multiple NgDocApi definitions, each with its own set of scopes. Then we could choose which ones are grouped together.

**Comment by skoropadas** [comment]
That's a good proposal, to be honest, I don't remember exactly why I banned the creation of multiple `NgDocApi` configurations, but it would be a good compromise!

**Comment by semicolin** [comment]
Thanks, I'll check it out
